plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
	id 'maven-publish'
	id "com.gradleup.shadow" version "9.6.0"

    id "com.modrinth.minotaur" version "2.+"
}

version = project.mod_version
group = project.maven_group

var versions = ["26.2"]

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
    gradlePluginPortal()
}

sourceSets {
    unitTest {
        java.srcDir('src/unitTest/java')
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"myworld_traffic_addition" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	accessWidenerPath = file("src/main/resources/myworld_traffic_addition.classtweaker")
}

configurations {
    unitTestImplementation.extendsFrom implementation
    unitTestRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation 'io.github.wasabithumb:jtoml:1.5.2'

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"

    unitTestImplementation 'io.github.wasabithumb:jtoml:1.5.2'
    unitTestImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    unitTestRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    unitTestRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // ImGuiB3D
    implementation "io.github.tobiazsh.imguib3d:${project.minecraft_version}:${project.imguib3d_version}"

    // Other dependencies
    include implementation("io.github.tobiazsh.jengua:Jengua:${project.jengua_version}") // Jengua; Translation library
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier = "shadow"
    enableAutoRelocation = true
    relocate "org.lwjgl", "at.tobias.myworld_traffic_addition.lwjgl"

    mergeServiceFiles()
}

loom.nestJars(tasks.named('shadowJar', org.gradle.jvm.tasks.Jar), objects.fileCollection().tap {
    it.setFrom(fileTree(tasks.processIncludeJars.outputDirectory))
    it.builtBy(tasks.processIncludeJars)
})

processResources {
    inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

tasks.build {
    dependsOn(shadowJar)
}

jar {
    enabled = true
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

test {
    useJUnitPlatform()
}


// PUBLISHING

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "myworld-traffic-addition"
    versionNumber = project.version
    versionType = "release"
    uploadFile = jar
    gameVersions = versions
    loaders = ["fabric"]
    dependencies {
        required.project "fabric-api"
    }
}

tasks.register('unitTest', Test) {
    useJUnitPlatform()
    testClassesDirs = sourceSets.unitTest.output.classesDirs
    classpath = sourceSets.unitTest.runtimeClasspath
}

tasks.named('check') { dependsOn 'unitTest' }

tasks.register("publishAll") {
    dependsOn("modrinth")
}


// JAVADOC

tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet')
}
