# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=1.8.1
maven_group=at.tobiazsh.myworld.traffic_addition
archives_base_name=myworld_traffic_addition

# FAPI
fabric_api_version=0.158.0+26.2

# Other Dependencies
jengua_version=1.2.2
imguib3d_version=1.0.2